# Generated by Django 6.0.4 on 2026-04-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_api_vehicle_route_21f689_idx_api_vehicle_route_i_33d88b_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['route', 'is_archived'], name='api_vehicle_route_i_33d88b_idx'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='intended_batch',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_late',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
