# Generated by Django 6.0.6 on 2026-06-29 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_driverrewardprofile_redemption_pointstransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketseries',
            name='beginning_balance',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketseries',
            name='beginning_balance_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
