# Generated by Django 6.0.6 on 2026-06-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_vehicle_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_per_redemption', models.IntegerField(default=1000)),
                ('peso_value_per_redemption', models.DecimalField(decimal_places=2, default=500, max_digits=10)),
                ('max_redemptions_per_year', models.IntegerField(default=2)),
                ('cooldown_months', models.IntegerField(default=6)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
