# Generated by Django 6.0.6 on 2026-06-30 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_rewardconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Denomination',
        ),
    ]
