# Generated by Django 6.0.6 on 2026-07-01 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_delete_denomination'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardconfig',
            name='daily_bonus_4_points',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='rewardconfig',
            name='daily_bonus_4_threshold',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='rewardconfig',
            name='daily_bonus_5_points',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='rewardconfig',
            name='daily_bonus_5_threshold',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='rewardconfig',
            name='monthly_bonus_days',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='rewardconfig',
            name='monthly_bonus_points',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='rewardconfig',
            name='points_per_queue',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='rewardconfig',
            name='streak_bonus_days',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='rewardconfig',
            name='streak_bonus_points',
            field=models.IntegerField(default=50),
        ),
    ]
