# Generated by Django 6.0.6 on 2026-07-02 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_rewardconfig_daily_bonus_4_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='batch',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
    ]
