# Generated by Django 6.0.6 on 2026-07-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_user_middle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='approved_by',
        ),
        migrations.AddField(
            model_name='requisition',
            name='approved_by_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
