# Generated by Django 6.0.6 on 2026-07-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_remove_requisition_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remittancebatch',
            name='batch_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
