# Generated by Django 6.0.6 on 2026-07-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_terminalprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='issuance_group',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
    ]
