# Generated by Django 6.0.6 on 2026-07-09 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_ticket_issuance_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverrewardprofile',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='redemption',
            name='profile',
        ),
        migrations.RemoveIndex(
            model_name='pointstransaction',
            name='api_pointst_profile_5a4f4f_idx',
        ),
        migrations.RemoveField(
            model_name='redemption',
            name='approved_by',
        ),
        migrations.DeleteModel(
            name='RewardConfig',
        ),
        migrations.RemoveField(
            model_name='pointstransaction',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Redemption',
        ),
        migrations.DeleteModel(
            name='DriverRewardProfile',
        ),
        migrations.DeleteModel(
            name='PointsTransaction',
        ),
    ]
