# Generated by Django 6.0.6 on 2026-07-09 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_remove_driverrewardprofile_driver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='intended_batch',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='is_late',
        ),
    ]
