# Generated by Django 6.0.6 on 2026-07-09 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_remove_ticket_batch_remove_ticket_intended_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='qr_code',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
