# Generated by Django 6.0.6 on 2026-07-10 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_driver_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketseries',
            name='qty',
        ),
    ]
