# Generated by Django 6.0.6 on 2026-07-12 23:11

import django.core.validators
from django.db import migrations, models


def copy_email_to_username(apps, schema_editor):
    User = apps.get_model('api', 'User')
    for user in User.objects.exclude(email=''):
        user.username = user.email
        user.save(update_fields=['username'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_remove_ticketseries_qty'),
    ]

    operations = [
        migrations.RunPython(copy_email_to_username, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that email already exists.'}, help_text='Used as the account email address and login.', max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')], verbose_name='email address'),
        ),
    ]
