# Generated by Django 6.0.6 on 2026-07-13 02:17

from django.db import migrations, models


def rename_admin_to_superadmin(apps, schema_editor):
    User = apps.get_model('api', 'User')
    User.objects.filter(role='ADMIN').update(role='SUPERADMIN')


def rename_superadmin_to_admin(apps, schema_editor):
    User = apps.get_model('api', 'User')
    User.objects.filter(role='SUPERADMIN').update(role='ADMIN')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_user_username_as_email'),
    ]

    operations = [
        migrations.RunPython(rename_admin_to_superadmin, rename_superadmin_to_admin),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PERSONNEL', 'Personnel'), ('SUPERVISOR', 'Supervisor'), ('MANAGER', 'Manager'), ('SUPERADMIN', 'Super Admin')], default='PERSONNEL', max_length=20),
        ),
    ]
