# Generated by Django 6.0.6 on 2026-07-26 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_rename_admin_role_to_superadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='queue_code',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
    ]
