# Generated by Django 6.0.6 on 2026-07-26 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_ticket_queue_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='remittancebatch',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='requisition',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
