# Generated by Django 6.0.6 on 2026-07-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_archive_requisition_remittance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_reset_password',
            field=models.BooleanField(default=False),
        ),
    ]
