# Generated by Django 6.0.6 on 2026-08-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_alter_user_role_super_admin_to_admin_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_label', models.CharField(db_index=True, max_length=100)),
                ('object_id', models.CharField(max_length=50)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('synced_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['queued_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='syncqueue',
            constraint=models.UniqueConstraint(fields=('model_label', 'object_id'), name='unique_sync_queue_object'),
        ),
    ]
