# Generated by Django 6.0.6 on 2026-08-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_syncqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncqueue',
            name='pending_delete',
            field=models.BooleanField(default=False),
        ),
    ]
