# Generated by Django 6.0.6 on 2026-08-16 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_name_snapshots(apps, schema_editor):
    # Capture names now, while the FK still points at a real user, for every
    # row that predates this migration — otherwise they'd stay blank forever
    # since Ticket.save()/Requisition.save() only fill this in on new saves.
    db_alias = schema_editor.connection.alias
    Ticket = apps.get_model('api', 'Ticket')
    Requisition = apps.get_model('api', 'Requisition')

    def display_name(user):
        return f"{user.first_name} {user.last_name}".strip() or user.username

    for ticket in Ticket.objects.using(db_alias).filter(active_user_name='', active_user__isnull=False):
        ticket.active_user_name = display_name(ticket.active_user)
        ticket.save(using=db_alias)

    for req in Requisition.objects.using(db_alias).filter(requested_by_name='', requested_by__isnull=False):
        req.requested_by_name = display_name(req.requested_by)
        req.save(using=db_alias)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_syncqueue_pending_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='requested_by_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='ticket',
            name='active_user_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='active_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_name_snapshots, migrations.RunPython.noop),
    ]
