# Generated by Django 6.0.6 on 2026-08-25 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_remittancebatch_covers_date'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
