# Generated by Django 6.0.6 on 2026-08-25 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
