# Generated by Django 6.0.6 on 2026-08-25 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_ticket_dispatched_at_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('ISSUED', 'Issued'), ('DISPATCHED', 'Dispatched'), ('COLLECTED', 'Collected'), ('CANCELLED', 'Cancelled')], default='ISSUED', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('QUEUED', 'Queued')], default='AVAILABLE', max_length=20),
        ),
    ]
