# Generated by Django 6.0.6 on 2026-08-25 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_trim_dead_status_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('ISSUED', 'Issued'), ('COLLECTED', 'Collected'), ('CANCELLED', 'Cancelled')], default='ISSUED', max_length=20),
        ),
    ]
