# Generated by Django 6.0.6 on 2026-08-25 05:02

from django.db import migrations, models


def rename_issued_to_queued(apps, schema_editor):
    Ticket = apps.get_model('api', 'Ticket')
    Ticket.objects.filter(status='ISSUED').update(status='QUEUED')


def rename_queued_to_issued(apps, schema_editor):
    Ticket = apps.get_model('api', 'Ticket')
    Ticket.objects.filter(status='QUEUED').update(status='ISSUED')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_remove_ticket_dispatched_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'Queued'), ('COLLECTED', 'Collected'), ('CANCELLED', 'Cancelled')], default='QUEUED', max_length=20),
        ),
        migrations.RunPython(rename_issued_to_queued, rename_queued_to_issued),
    ]
