# Generated by Django 6.0.6 on 2026-08-25 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_rename_ticket_issued_to_queued'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteBackfillRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField()),
                ('ticket_id', models.CharField(blank=True, default='', max_length=50)),
                ('requested_by_name', models.CharField(blank=True, default='', max_length=150)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPLIED', 'Applied'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('result_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
