# Generated by Django 6.0.3 on 2026-09-06 01:24

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_driver_middle_name_optional'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveIndex(
            model_name='vehicle',
            name='api_vehicle_route_i_33d88b_idx',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
