# Generated by Django 6.0.6 on 2026-09-23 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_user_email_verified'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
