"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# Local dev: leave DEBUG unset in backend/.env (defaults to True).
# Production: set DEBUG=False in the environment.
DEBUG = os.getenv('DEBUG', 'True') == 'False'

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'daphne',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'corsheaders',
    'rest_framework',
    'channels',
    'api',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'
ASGI_APPLICATION = 'backend.asgi.application'

# Dev-only channel layer (single-process, in-memory). Swap for
# channels_redis.core.RedisChannelLayer if running multiple workers/processes.
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# 'default' is always SQLite — the LAN source of truth for live transactions,
# and it must keep working with no internet connection. DEBUG picks WHICH
# file: a throwaway one for local test runs vs. a separate one for the real
# terminal, so test data never mixes with real operational data.
#
# 'supabase' is the remote Postgres mirror, used only by the sync engine
# (api/sync/) — never by regular app code. It pushes LAN transactions out
# for read-only remote viewing, and pulls down settings/records that
# admin/manager edit remotely. Pushing is disabled while DEBUG=True (see
# api/sync/push.py) so local test runs can never leak into the shared
# remote mirror that real users see.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / ('db.sqlite3' if DEBUG else 'db_production.sqlite3'),
        # SQLite only allows one writer at a time; two staff dispatching tickets
        # at the same moment is entirely realistic at a live terminal, and
        # without an explicit timeout the second writer gets "database is
        # locked" immediately instead of just waiting its turn.
        # SQLite only allows one writer at a time; two staff dispatching tickets
        # at the same moment is entirely realistic at a live terminal, and
        # without an explicit timeout the second writer gets "database is
        # locked" immediately instead of just waiting its turn.
        'OPTIONS': {'timeout': 20},
    },
    'supabase': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT', '5432'),
        'OPTIONS': {'sslmode': 'require'},
        'CONN_MAX_AGE': 60,
    },
}

# Sync engine (LAN SQLite <-> Supabase mirror) — see api/sync/
SYNC_INTERVAL_SECONDS = int(os.getenv('SYNC_INTERVAL_SECONDS', '30'))
SYNC_BATCH_SIZE = int(os.getenv('SYNC_BATCH_SIZE', '200'))


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

CORS_ALLOW_ALL_ORIGINS = True

CSRF_TRUSTED_ORIGINS = ['http://localhost:3000', 'http://localhost:5174', 'http://localhost:5173']

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny' if DEBUG else 'rest_framework.permissions.IsAuthenticated',
    ],
}

AUTH_USER_MODEL = 'api.User'

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=5),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
}

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Email (Google SMTP)
# EMAIL_HOST_USER / EMAIL_HOST_PASSWORD / DEFAULT_FROM_EMAIL come from backend/.env
# (see backend/.env.example). Use a Gmail "App Password" (not your normal Google
# account password) — https://myaccount.google.com/apppasswords
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)

# Base URL of the frontend app, used to build the password-reset link sent by email
FRONTEND_URL = 'http://localhost:5173'

# Sync engine logging — last N cycles are always visible on the console;
# also kept in a small rotating file so `sync_worker` running unattended
# still leaves a trail of what synced and what didn't.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'sync': {'format': '%(asctime)s %(levelname)s %(message)s'},
    },
    'handlers': {
        'sync_console': {
            'class': 'logging.StreamHandler',
            'formatter': 'sync',
        },
        'sync_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'sync.log',
            'maxBytes': 1024 * 1024,
            'backupCount': 2,
            'formatter': 'sync',
        },
    },
    'loggers': {
        'sync': {
            'handlers': ['sync_console', 'sync_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
